### ISSUE TITLE
2.1 CAD de los 3 productos

### ISSUE THREAD

**Issue by caverar** [APM-Kullu/Project#2]

**Comment by caverar** [comment]
Terminado, solo falta que todos suban el archivo al repo.

**Comment by caverar** [comment]
Pendiente Julián y Juan por subir archivo.  Julián importante corregir unidades del archivo. IMPORTANTE: formato .step único archivo de ensamble debido a que nos contabilizaran el porcentaje de aporte de cada uno mediante GitHub.

**Comment by julianVelandia** [comment]
Los archivos de las piezas de la estantería de vinos ya se encontraban en la carpeta de Drive (Al igual que los del compañero Juan), sin embargo se sube una carpeta con los archivos .STEP, .DWG y .PDF con la convención de medidas acordada
