### ISSUE TITLE
Organización de plantilla para web de proyecto

### ISSUE THREAD

**Issue by caverar** [APM-Kullu/Project#5]

**Comment by caverar** [comment]
Finalizar a mas tardar el miércoles 1 de marzo, teniendo en cuenta otras paginas como: https://art3chautomation.github.io/WarePatch/Home.html, https://leonardomercado.github.io/Proyecto_APM/03%20Pagina%20web/index.html, https://apm2021-1.github.io/BICIBU-Pagina-web/

**Comment by julianVelandia** [comment]
Ya se había subido y desplegado una primera versión, sin embargo, se subieron más cambios con las referencias anteriores [PR](https://github.com/APM-Kullu/kulluWebSite/pull/1)
